USE [TruckWeigh]
GO
GRANT EXECUTE TO "TRAFGLOBAL\PrecisionUAT"
GO
USE [ONL_PE_TRAFIGURA]
GO
GRANT EXECUTE TO "TRAFGLOBAL\OnLIMSUAT"
GO
USE [ONL_MX_TRAFIGURA]
GO
GRANT EXECUTE TO "TRAFGLOBAL\OnLIMS_MX_UAT"
GO
USE [ONL_CL_TRAFIGURA]
GO
GRANT EXECUTE TO "TRAFGLOBAL\OnLIMS_CH_UAT"


