USE [TruckWeigh]
GO
GRANT EXECUTE TO "TRAFGLOBAL\PrecisionPROD"
GO
USE [ONL_PE_TRAFIGURA]
GO
GRANT EXECUTE TO "TRAFGLOBAL\OnLIMS_PE_PRD"
GO
USE [ONL_MX_TRAFIGURA]
GO
GRANT EXECUTE TO "TRAFGLOBAL\OnLIMS_MX_PRD"
GO
USE [ONL_CL_TRAFIGURA]
GO
GRANT EXECUTE TO "TRAFGLOBAL\OnLIMS_CL_PRD"


